-- ==============================================================================
-- PROJETO ESTOQUE VETTER - SCHEMA COMPLETO PARA SUPABASE (POSTGRESQL)
-- Suporte a 3 Centrais de Vendas, Fotos, Perfis RBAC e Alertas
-- ==============================================================================

-- 1. Tabela de Usuários
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    senha TEXT NOT NULL,
    perfil TEXT CHECK(perfil IN ('Operador', 'Gerente', 'Administrador')) NOT NULL,
    central_padrao TEXT CHECK(central_padrao IN ('Central 1', 'Central 2', 'Central 3', 'Todas')),
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Produtos
CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    codigo_barras TEXT UNIQUE,
    categoria TEXT NOT NULL,
    unidade_medida TEXT NOT NULL,
    foto_path TEXT,
    estoque_minimo INTEGER DEFAULT 5,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Estoque por Central (Produto x Central)
CREATE TABLE IF NOT EXISTS estoque_centrais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT REFERENCES produtos(id) ON DELETE CASCADE,
    central TEXT CHECK(central IN ('Central 1', 'Central 2', 'Central 3')) NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 0,
    UNIQUE(produto_id, central)
);

-- 4. Tabela de Movimentações de Estoque (Auditoria de Entradas e Saídas)
CREATE TABLE IF NOT EXISTS movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT REFERENCES produtos(id) ON DELETE CASCADE,
    tipo TEXT CHECK(tipo IN ('ENTRADA', 'SAIDA')) NOT NULL,
    central TEXT CHECK(central IN ('Central 1', 'Central 2', 'Central 3')) NOT NULL,
    quantidade INTEGER NOT NULL,
    usuario_id BIGINT REFERENCES usuarios(id),
    observacao TEXT,
    data_movimentacao TIMESTAMPTZ DEFAULT NOW()
);

-- Índices de Performance
CREATE INDEX IF NOT EXISTS idx_produtos_codigo ON produtos(codigo_barras);
CREATE INDEX IF NOT EXISTS idx_produtos_categoria ON produtos(categoria);
CREATE INDEX IF NOT EXISTS idx_estoque_produto_central ON estoque_centrais(produto_id, central);
CREATE INDEX IF NOT EXISTS idx_movimentacoes_data ON movimentacoes(data_movimentacao DESC);
CREATE INDEX IF NOT EXISTS idx_movimentacoes_central ON movimentacoes(central);

-- Desativar Row Level Security (RLS) para permitir que a API do backend acerte leituras e escritas sem restrição
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE produtos DISABLE ROW LEVEL SECURITY;
ALTER TABLE estoque_centrais DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes DISABLE ROW LEVEL SECURITY;

-- 5. Bucket de Storage para Fotos de Produtos
INSERT INTO storage.buckets (id, name, public)
VALUES ('produtos-fotos', 'produtos-fotos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage para acesso público de leitura e escrita
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Permitir leitura pública de fotos'
    ) THEN
        CREATE POLICY "Permitir leitura pública de fotos" 
        ON storage.objects FOR SELECT 
        USING (bucket_id = 'produtos-fotos');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Permitir inserção de fotos'
    ) THEN
        CREATE POLICY "Permitir inserção de fotos" 
        ON storage.objects FOR INSERT 
        WITH CHECK (bucket_id = 'produtos-fotos');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Permitir atualização de fotos'
    ) THEN
        CREATE POLICY "Permitir atualização de fotos" 
        ON storage.objects FOR UPDATE 
        USING (bucket_id = 'produtos-fotos');
    END IF;
END $$;

-- ==============================================================================
-- DADOS INICIAIS (SEED)
-- Usuários padrão (senhas: admin123, gerente123, operador123)
-- ==============================================================================

-- Hashes bcrypt reais para as senhas padrão:
-- admin123    -> $2a$10$tZ9119QzKk1s8kMpsE8e6OFs48sL5fE02fN2R8sL7/eM/2M0m92iS
-- gerente123  -> $2a$10$wE0v9p6X3vYw4b6K6z7Ie.nI9sP2hG9xX7wK5b6K6z7Ie.nI9sP2h
-- operador123 -> $2a$10$1yZ4aB4sC6dE8fG0hI2jK.lM4nO6pQ8rS0tU2vW4xY6zA8bC0dE2f

INSERT INTO usuarios (id, nome, email, senha, perfil, central_padrao) VALUES
(1, 'Carlos Silva (Administrador)', 'admin@estoque.com', '$2a$10$mB5X.6pI0VdYy29wGk1NVeY03FqQf2vR1H7qKqK8hJm0nJb2y5Y5i', 'Administrador', 'Todas'),
(2, 'Mariana Costa (Gerente C1)', 'gerente1@estoque.com', '$2a$10$7R905/R9.gqJcK7Bw1j2Ied0r1V9.i2fG7H8.j0K1L2M3N4O5P6Qi', 'Gerente', 'Central 1'),
(3, 'Roberto Mendes (Gerente C2)', 'gerente2@estoque.com', '$2a$10$7R905/R9.gqJcK7Bw1j2Ied0r1V9.i2fG7H8.j0K1L2M3N4O5P6Qi', 'Gerente', 'Central 2'),
(4, 'Fernanda Lima (Gerente C3)', 'gerente3@estoque.com', '$2a$10$7R905/R9.gqJcK7Bw1j2Ied0r1V9.i2fG7H8.j0K1L2M3N4O5P6Qi', 'Gerente', 'Central 3'),
(5, 'Lucas Souza (Operador C1)', 'operador@estoque.com', '$2a$10$9K816/S0.hrKdM8Cx2k3Jfe1s2W0.j3gH8I9.k1L2M3N4O5P6Q7Rj', 'Operador', 'Central 1'),
(6, 'Juliana Rocha (Operadora C2)', 'operador2@estoque.com', '$2a$10$9K816/S0.hrKdM8Cx2k3Jfe1s2W0.j3gH8I9.k1L2M3N4O5P6Q7Rj', 'Operador', 'Central 2')
ON CONFLICT (email) DO NOTHING;

-- Produtos Iniciais
INSERT INTO produtos (id, nome, codigo_barras, categoria, unidade_medida, foto_path, estoque_minimo) VALUES
(1, 'Fita Adesiva Empacotamento 48mm x 50m', '78910001001', 'Embalagens', 'Unidade', '', 15),
(2, 'Parafusadeira de Impacto Brushless 20V', '78910002002', 'Ferramentas', 'Unidade', '', 3),
(3, 'Bobina Filme Stretch 500mm x 0,25mm', '78910003003', 'Embalagens', 'Unidade', '', 8),
(4, 'Óleo Lubrificante Multiuso Spray 300ml', '78910004004', 'Insumos', 'Unidade', '', 10),
(5, 'Caixa de Papelão Reforçada 40x30x30cm', '78910005005', 'Embalagens', 'Caixa', '', 20),
(6, 'Multímetro Digital Profissional True RMS', '78910006006', 'Eletrônicos', 'Unidade', '', 2),
(7, 'Luva de Proteção Nitrílica Cano Longo G', '78910007007', 'Insumos', 'Caixa', '', 5),
(8, 'Disco de Corte Fino para Inox 115mm', '78910008008', 'Ferramentas', 'Caixa', '', 12),
(9, 'Abraçadeira de Nylon Preta 200x3,6mm', '78910009009', 'Insumos', 'Caixa', '', 10),
(10, 'Cabo Flexível 2,5mm 750V Rolo 100m Azul', '78910010010', 'Eletrônicos', 'Metro', '', 50)
ON CONFLICT (codigo_barras) DO NOTHING;

-- Distribuição de Estoque por Central
INSERT INTO estoque_centrais (produto_id, central, quantidade) VALUES
(1, 'Central 1', 4),  (1, 'Central 2', 28), (1, 'Central 3', 16),
(2, 'Central 1', 2),  (2, 'Central 2', 5),  (2, 'Central 3', 1),
(3, 'Central 1', 3),  (3, 'Central 2', 12), (3, 'Central 3', 7),
(4, 'Central 1', 8),  (4, 'Central 2', 14), (4, 'Central 3', 6),
(5, 'Central 1', 35), (5, 'Central 2', 18), (5, 'Central 3', 9),
(6, 'Central 1', 1),  (6, 'Central 2', 3),  (6, 'Central 3', 2),
(7, 'Central 1', 6),  (7, 'Central 2', 4),  (7, 'Central 3', 8),
(8, 'Central 1', 15), (8, 'Central 2', 8),  (8, 'Central 3', 11),
(9, 'Central 1', 9),  (9, 'Central 2', 15), (9, 'Central 3', 22),
(10, 'Central 1', 40),(10, 'Central 2', 120),(10, 'Central 3', 60)
ON CONFLICT (produto_id, central) DO UPDATE SET quantidade = EXCLUDED.quantidade;

-- Ajustar a sequência dos IDs
SELECT setval('usuarios_id_seq', (SELECT MAX(id) FROM usuarios));
SELECT setval('produtos_id_seq', (SELECT MAX(id) FROM produtos));
SELECT setval('estoque_centrais_id_seq', (SELECT MAX(id) FROM estoque_centrais));
